import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { DarkModeToggle } from '@/src/components/DarkModeToggle'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  modal,
  children,
}: Readonly<{
  modal: React.ReactNode;
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={'bg-neutral-100 dark:bg-neutral-900 dark:text-neutral-50'}
    >
      <body className={inter.className}>
        <div className={'mx-auto max-w-container'}>
          <DarkModeToggle />
          {modal}
          {children}
        </div>
      </body>
    </html>
  );
}
