import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { DarkModeToggle } from '@/src/components/DarkModeToggle'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={'dark:bg-neutral-800 dark:text-neutral-50'}
    >
      <body className={inter.className}>
        <DarkModeToggle />
        {children}
      </body>
    </html>
  );
}
