import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from 'sonner'
import { TopNavbar } from '@/src/components/TopNavbar'
import { SideNavbar } from '@/src/components/SideNavbar'
import classNames from 'classnames'
import { TopNavbarHeight } from '@/src/components/helpers/TopNavbarHeight'
import { SideNavbarWidth } from '@/src/components/helpers/SideNavbarWidth'

const inter = Inter({
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	modal,
	children
}: Readonly<{
  modal: React.ReactNode;
  children: React.ReactNode;
}>) {
	return (
		<html
			lang={'en'}
			className={'bg-neutral-100 dark:bg-neutral-900 dark:text-neutral-50'}
		>
			<body
				className={classNames(
					inter.className,
					'min-h-screen'
				)}
			>
				<Toaster />
				<TopNavbar />
				<div
					className={'flex items-start'}
				>
					<SideNavbar />
					<SideNavbarWidth />
					<main
						className={'pt-4 lg:pt-8 pb-10 lg:pb-20 mx-auto px-3 lg:px-8 w-full max-w-container'}
					>
						<TopNavbarHeight />
						{ modal }
						{ children }
					</main>
				</div>
			</body>
		</html>
	)
}
